services:
  whatsapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-baileys
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./sessions:/usr/src/app/sessions
    ports:
      - "3001:3001"
    restart: unless-stopped
